package com.whx.entities;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

// Generated 2018-3-18 17:04:40 by Hibernate Tools 5.1.6.Final

/**
 * TUser generated by hbm2java
 */
@Entity
@Table(name="t_user")
public class TUser implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	@Id
	private String account;
	
	@Column
	private String password;
	
	@Column
	private String category;
	
	@Column
	private String phone;
	
	@Column
	private String concerns;
	
	@Column
	private Short contributions;

	public TUser() {
	}

	public TUser(String account, String password, String category) {
		this.account = account;
		this.password = password;
		this.category = category;
	}

	public TUser(String account, String password, String category, String phone, String concerns, Short contributions) {
		this.account = account;
		this.password = password;
		this.category = category;
		this.phone = phone;
		this.concerns = concerns;
		this.contributions = contributions;
	}

	public String getAccount() {
		return this.account;
	}

	public void setAccount(String account) {
		this.account = account;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getCategory() {
		return this.category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getConcerns() {
		return this.concerns;
	}

	public void setConcerns(String concerns) {
		this.concerns = concerns;
	}

	public Short getContributions() {
		return this.contributions;
	}

	public void setContributions(Short contributions) {
		this.contributions = contributions;
	}
}